version: "3.3"

services:
  db:
    image: postgres:14-alpine
    secrets:
      - db_user
      - db_password
      - db_name
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/db_data
      o: bind

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true

networks:
  backend:
    external: true
