version: "3.3"

services:
  app:
          image: fstresau/my-flask-image:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpass
    ports:
      - "80:5000"
    networks:
      - backend

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: overlay

volumes:
  db_data:

