version: "3.3"

services:
  app:
    image: fstresau/sebs-flask-image:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpass
      - POSTGRES_DB=flaskdb
    ports:
      - "80:8080"
    networks:
      - backend

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=flaskdb
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: overlay

volumes:
  db_data:

